CleanArch_Project/RazorSample/Pages/Account/Info/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;
using ApplicationCore.Services;
using ApplicationCore.DTOs;
using Web.Services;
using Web.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Web.Pages.Account.Info
{
    public class DetailsModel : PageModel
    {
        private readonly UserVmService _service;

        public DetailsModel(UserVmService service)
        {
            _service = service;
        }

        public UserDto User { get; set; }


        public UserVm userVm { get; set; }
        public IActionResult OnGet(int id)
        {

            //neu da dang nhap
            if(HttpContext.Session.GetString("username") != null)
            {

              
                    userVm = _service.GetUserViewModel(id);
              
                    
                
               
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }


            
        }
    }
}

CleanArch_Project/RazorSample/Pages/Basket/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.DTOs;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Basket
{
    public class ViewModel : PageModel
    {
        private readonly ProductService _service;
        private readonly OrderService _service1;

        public ViewModel(ProductService service, OrderService service1)
        {
            _service = service;
            _service1 = service1;
        }

        [BindProperty]
        public Order Order { get; set; }
        [BindProperty]
        public OrderDetail OrderDetail { get; set; }
        [BindProperty]
        public List<Item> cart { get; set; }

        public List<Product> Products { get; set; }
        public double Total { get; set; }

        [BindProperty(SupportsGet = true)]
        public string message { get; set; }

        public IActionResult OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                Total = cart.Sum(i => i.Product.ProductPrice * i.Quantity);
                return Page();
            }
            else
            {
                Total = 0;
                return Page();
            }

        }

        public IActionResult OnGetBuyNow(int id)
        {
            //lay list<Product>

            Products = _service.GetListProducts().ToList<Product>();



            //lay session list<Item>
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else    //neu da ton tai item do thi chi can them 1 so luong
            {


                int index = Exists(cart, id);
                if (index == -1)  //neu chua co id trong cart thi them moi
                {
                    cart.Add(new Item
                    {
                        Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                        Quantity = 1
                    });
                }
                else   //ton tai thi tang so luong thoi
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("/Basket/View");
        }

        // xoa item trong cart

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        // update quantity trong session
        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        //kiem tra id san pham da ton tai trong cart chua
        //neu ton tai thi tra ve id
        //neu khong thi tra ve -1

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }


        //thanhtoan
        public IActionResult OnPostThanhToan()
        {

            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (HttpContext.Session.GetString("username") == null)
            {
                message = "Ban chua dang nhap";
            }
            else
            {
                _service1.AddOrder(HttpContext.Session.GetString("username"), Order, cart, OrderDetail);

                //xoa session
                HttpContext.Session.Remove("cart");


            }

                return Page();
            
        }

    }
}

CleanArch_Project/RazorSample/Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using ApplicationCore.DTOs;

namespace Web.Pages.Products
{
    public class DetailsModel : PageModel
    {
       
            private readonly ProductService _service;

            public DetailsModel(ProductService service)
            {
                _service = service;
            }

            public ProductDto Product { get; set; }

            public IActionResult OnGet(int id)
            {
                Product = _service.GetProduct(id);

                if (Product == null)
                {
                    return NotFound();
                }
                return Page();
            }
        }
}

CleanArch_Project/RazorSample/Pages/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Services;
using Web.ViewModels;

namespace Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly ProductListVmService _ProductService;
        public IndexModel(ProductListVmService ProductService)
        {
            _ProductService = ProductService;
        }

        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }

      

        [BindProperty(SupportsGet = true)]
        public string typename { get; set; }

        [BindProperty(SupportsGet = true)]
        public string sort{ get; set; }

        public ProductListVm ProductIndexVM { get; set; }
        public void OnGet(int pageIndex=1)
        {
            if(sort == "giam")
            {
              
                ProductIndexVM = _ProductService.GetProductPriceDecrease(CurrentFilterProduct, typename, pageIndex);

            }
            else
            {
                ProductIndexVM = _ProductService.GetProductIndexViewModel(CurrentFilterProduct, typename, pageIndex);
            }

          


        }
        



    }
}

CleanArch_Project/RazorSample/Pages/Products/Details.cshtml
@page
@model Web.Pages.Products.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductQuantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductQuantity)
        </dd>
       
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductProvider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductProviderId)
        </dd>
       
        
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Product.ProductId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

CleanArch_Project/RazorSample/Pages/Products/Index.cshtml
@page

@model IndexModel
@{
    ViewData["Title"] = "Product";
}
<h2>Index</h2>

<!--render sections-->

@section headers{


    @if (@HttpContext.Session.GetString("username") != null)
    {
        <p>xin chao <a asp-page="/users/details" asp-route-id="@HttpContext.Session.GetString("userid")">@HttpContext.Session.GetString("username")</a></p>

        <form method="post">
            <input asp-page="/Account/Login/Dangnhap" asp-page-handler="logout" type="submit" value="Log out" />

        </form>



    }
    else    //chua dang nhap
    {
        <a asp-page="/Account/Login/DangNhap">Dang nhap</a>
        <a asp-page="/Account/Register/DangKy">Dang ky </a>
    }

    <!--Search -->
    <form method="get">

        <input type="text" asp-for="CurrentFilterProduct" />
        <input asp-page="/Products/index" type="submit" value="Search" class="btn btn-default" />
    </form>
}


<style>

    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 200px;
        margin: auto;
        text-align: center;
        margin-top: 15px;
        font-family: arial;
        float: left;
        margin-left: 15px;
    }

    .img_frame {
        width: 200px;
        height: 250px;
        float: left;
        overflow: hidden;
        position: relative;
    }

    .blank_img {
        width: 200px;
        height: 250px;
        background-color: black;
        float: left;
    }

    .price {
        color: grey;
        font-size: 22px;
    }

    .img_frame img {
        transition: .3s ease-in;
    }

    .img_frame:hover img {
        transform: scale(1.3);
    }

    .card button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

        .card button:hover {
            opacity: 0.7;
        }

    .container1 {
        float: initial;
    }
</style>


<form method="get">
    <p>
        <select asp-for="typename" asp-items="Model.ProductIndexVM.Genres">
            <option value="">All</option>
        </select>

        Find by name: <input type="text" asp-for="CurrentFilterProduct" />


       

        <input type="submit" />

        <a asp-page="./index" asp-route-sort="giam">Price Decrease</a>
    </p>
</form>




<form method="post">

    @foreach (var Product in Model.ProductIndexVM.Products)
    {

        <div class="card">
            <div class="img_frame">

                <img src="~/Image/chuot.jpg" alt="Denim Jeans" style="width:200px;height:250px">



            </div>

            <a asp-page="./Details" asp-route-id="@Product.ProductId">
                <p> @Product.ProductName</p>
            </a>
            <p class="price">@Product.ProductPrice</p>
            <p>
                <button>
                    <a asp-page="/Basket/View" asp-page-handler="buynow"
                       asp-route-id=@Product.ProductId >Buy Now</a>
                </button>
            </p>
        </div>

    }


    <!--
    SIMPLE CARD PRODUCT

                <td>
                    <button type="submit" asp-page-handler="Delete" asp-route-id="Product.ProductId">Delete</button>
                    <a asp-page="/Movies/Edit" asp-route-id="Product.ProductId">Edit</a>
                </td>
     -->



</form>
<br />
@{
    var preDisabled = !Model.ProductIndexVM.Products.HasPrevious ? "disabled" : "";
    var nextDisabled = !Model.ProductIndexVM.Products.HasNext ? "disabled" : "";
}
<div class="container1">
    <a asp-page="Index"
       asp-route-pageIndex="@(Model.ProductIndexVM.Products.PageIndex - 1)"
       class="btn btn-default @preDisabled">Previous</a>

    <a asp-page="Index"
       asp-route-pageIndex="@(Model.ProductIndexVM.Products.PageIndex + 1)"
       class="btn btn-default @nextDisabled">Next</a>
</div>