CleanArch_Project/RazorSample/Pages/Basket/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.DTOs;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Basket
{
    public class ViewModel : PageModel
    {
        private readonly ProductService _service;
        private readonly OrderService _service1;

        public ViewModel(ProductService service, OrderService service1)
        {
            _service = service;
            _service1 = service1;
        }

        [BindProperty]
        public Order Order { get; set; }
        [BindProperty]
        public OrderDetail OrderDetail { get; set; }
        [BindProperty]
        public List<Item> cart { get; set; }

        public List<Product> Products { get; set; }
        public double Total { get; set; }

        [BindProperty(SupportsGet = true)]
        public string message { get; set; }

        public IActionResult OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                Total = cart.Sum(i => i.Product.ProductPrice * i.Quantity);
                return Page();
            }
            else
            {
                Total = 0;
                return Page();
            }

        }

        public IActionResult OnGetBuyNow(int id)
        {
            //lay list<Product>

            Products = _service.GetListProducts().ToList<Product>();



            //lay session list<Item>
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else    //neu da ton tai item do thi chi can them 1 so luong
            {


                int index = Exists(cart, id);
                if (index == -1)  //neu chua co id trong cart thi them moi
                {
                    cart.Add(new Item
                    {
                        Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                        Quantity = 1
                    });
                }
                else   //ton tai thi tang so luong thoi
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("/Basket/View");
        }

        // xoa item trong cart

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        // update quantity trong session
        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        //kiem tra id san pham da ton tai trong cart chua
        //neu ton tai thi tra ve id
        //neu khong thi tra ve -1

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }


        //thanhtoan
        public IActionResult OnPostThanhToan()
        {

            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (HttpContext.Session.GetString("username") == null)
            {
                message = "Ban chua dang nhap";
            }
            else
            {
                _service1.AddOrder(HttpContext.Session.GetString("username"), Order, cart, OrderDetail);

                //xoa session
                HttpContext.Session.Remove("cart");


            }

                return Page();
            
        }

    }
}

CleanArch_Project/RazorSample/Pages/Basket/View.cshtml
@page
@model Web.Pages.Basket.ViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>

    @if (Model.cart == null)
    {

        //ko hien thi bang gio hanh
    }

    else
    {
        <div id="maincontent">
            <div class="container">
                <div>
                    <h2 class="text-center">Chi tiết giỏ hàng</h2>


                    <div class="container">
                        <table id="cart" class="table table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th style="width:50%">Tên sản phẩm</th>
                                    <th style="width:10%">Giá</th>
                                    <th style="width:8%">Số lượng</th>
                                    <th style="width:22%" class="text-center">Thành tiền</th>
                                    <th style="width:10%"> </th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.cart)
                                {
                                    <tr>
                                        <td data-th="Product">
                                            <div class="row">
                                                <div class="col-sm-2 hidden-xs">
                                                    <img src="#" alt="Sản phẩm " class="img-responsive" width="100">
                                                </div>
                                                <div class="col-sm-10">
                                                    <h4 class="nomargin">@item.Product.ProductName</h4>
                                                </div>
                                            </div>
                                        </td>
                                        <td data-th="Price">$@item.Product.ProductPrice</td>
                                        <td data-th="Quantity">
                                            <input class="form-control text-center" value="@item.Quantity" type="number">
                                        </td>
                                        <td data-th="Subtotal" class="text-center">$@(item.Product.ProductPrice * item.Quantity)</td>
                                        <td class="actions" data-th="">
                                            <button class="btn btn-info btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash-o"></i>
                                            </button>
                                        </td>
                                    </tr>

                                }
                                <tr>
                                    <td colspan="6" align="right">Total</td>
                                    <td align="center">$@Model.Total</td>
                                </tr>
                                <form method="post">
                                    
                                    <input asp-page-handler="thanhtoan" asp-page="/Basket/View" type="submit" value="ThanhToan" />

                                </form>

                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td>
                                        <a asp-page="/Products/index" class="btn btn-warning"><i class="fa fa-angle-left"></i> Tiếp tục mua hàng</a>
                                    </td>
                                    <td colspan="2" class="hidden-xs"> </td>
                                    <td class="hidden-xs text-center">
                                        <strong>Tổng tiền</strong>
                                    </td>
                                    <td>
                                        <a href="#" class="btn btn-success btn-block">Thanh toán <i class="fa fa-angle-right"></i></a>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>

                        <p style="color:red">@Model.message</p>
                    </div>
                </div>
            </div>
        </div>
    }
        <script src="~/js/slick.min.js"></script>
    </body>
</html>